@Library('corda-shared-build-pipeline-steps@knguyen/CORE-9883/improve_pr_comment') _

cordaPipeline(
    nexusAppId: 'com.corda.CSDE-kotlin.5.0',
    publishRepoPrefix: '',
    slimBuild: true,
    runUnitTests: false,
    dedicatedJobForSnykDelta: false,
    slackChannel: '#corda-corda5-dev-ex-build-notifications',
    gitHubComments: true
    )
