@Library('corda-shared-build-pipeline-steps@chrisbarratt/CORE-8075-create-pipeline-for-running-the-autotester') _

cordaPipeline(
    nexusAppId: 'com.corda.CSDE-kotlin.5.0',
    publishRepoPrefix: '',
    slimBuild: true,
    runUnitTests: false,
    dedicatedJobForSnykDelta: false,
    slackChannel: '#corda-corda5-dev-ex-build-notifications'
    )
